name: textify_dashboard
description: "Explore the Textify pacakage."
publish_to: "none"
version: 1.0.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl:
  path_provider: ^2.1.4
  pasteboard: ^0.3.0
  shared_preferences: ^2.2.2

  textify:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
    - assets/samples/
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: Courier
      fonts:
        - asset: assets/fonts/courier_new.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times_new_roman.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios:
    remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
